trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker hub'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
    includeLatestTag: true
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker hub'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
    includeLatestTag: true
